### ISSUE TITLE
Automate Release to docker.io

### ISSUE THREAD

**Issue by rymsha** [enonic/docker-xp#3]
Github Action:
When `.env` XP_VERSION changes to non-SNAPSHOT in a push in 7.x branch call `push-to-registry.sh`

**Comment by rymsha** [comment]
@gbbirkisson you may do it, probably. Look how it is done in XP, for instance

**Comment by rymsha** [comment]
@jsi You may need to explain to @gbbirkisson how you do it manually these days.

**Comment by jsi** [comment]
Had a workshop with Sergey today about this: I have started the work in `.github/workflow/docker-main.yml`.

What remains is to find a way to include variables from `.env`,  then convert the job of `.push-to-registry.sh` into GitHub actions.  Sergey thinks login to Docker Hub should be done as late as possible.

**Comment by jsi** [comment]
These are good resources for the job ahead:
- https://www.docker.com/blog/docker-v2-github-action-is-now-ga/
- https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

**Comment by rymsha** [comment]
> There's an action for that (c)

https://github.com/marketplace/actions/environment-variables-from-dotenv
