### ISSUE TITLE
Use of obsolete `adoptopenjdk:11-jre-hotspot` base image

### ISSUE THREAD

**Issue by rymsha** [enonic/docker-xp#8]
It is `eclipse-temurin:11-jre` that should be in use.

**Comment by gbbirkisson** [comment]
According to `trivy`, the base image you suggest has more vulnerabilities:

```console
$ trivy image adoptopenjdk:11-jre-hotspot
2022-01-03T12:37:59.486+0100	INFO	Detected OS: ubuntu
2022-01-03T12:37:59.486+0100	INFO	Detecting Ubuntu vulnerabilities...
2022-01-03T12:37:59.490+0100	INFO	Number of language-specific files: 0

adoptopenjdk:11-jre-hotspot (ubuntu 20.04)
==========================================
Total: 60 (UNKNOWN: 0, LOW: 48, MEDIUM: 12, HIGH: 0, CRITICAL: 0)
```

```console
$ trivy image eclipse-temurin:11-jre
2022-01-03T12:38:34.604+0100	INFO	Detected OS: ubuntu
2022-01-03T12:38:34.605+0100	INFO	Detecting Ubuntu vulnerabilities...
2022-01-03T12:38:34.611+0100	INFO	Number of language-specific files: 0

eclipse-temurin:11-jre (ubuntu 20.04)
=====================================
Total: 68 (UNKNOWN: 0, LOW: 52, MEDIUM: 16, HIGH: 0, CRITICAL: 0)
```

**Comment by rymsha** [comment]
This issue in not primarily not about vulnerabilities, but rather about use of obsolete docker image

**Comment by gbbirkisson** [comment]
> This issue in not primarily not about vulnerabilities, but rather about use of obsolete docker image

Since you mentioned this issue in https://github.com/enonic/xp/issues/9280, I thought it was relevant to make this clear.

**Comment by rymsha** [comment]
I filed another one #11

**Comment by rymsha** [comment]
> According to trivy, the base image you suggest has more vulnerabilities

This is because 
- newest image needs python libraries (a choice from openjdk developers?)
- current version trivy does not disambiguate CVEs (so actually there are only two more and none of them are fortunately relevant to us)
